"""migration

Revision ID: 22b20d38c9ee
Revises: d8a88420cda4
Create Date: 2024-07-18 13:02:23.215227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b20d38c9ee'
down_revision: Union[str, None] = 'd8a88420cda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('picture', sa.String(), nullable=True))
    op.drop_index('ix_profiles_location', table_name='profiles')
    op.create_index(op.f('ix_profiles_picture'), 'profiles', ['picture'], unique=False)
    op.drop_column('profiles', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_profiles_picture'), table_name='profiles')
    op.create_index('ix_profiles_location', 'profiles', ['location'], unique=False)
    op.drop_column('profiles', 'picture')
    # ### end Alembic commands ###
