"""migration

Revision ID: 8b2321973b25
Revises: 3213c14f7038
Create Date: 2024-07-19 15:59:18.651717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2321973b25'
down_revision: Union[str, None] = '3213c14f7038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_projects',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='user_projects_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_projects_user_id_fkey')
    )
    # ### end Alembic commands ###
