"""migration

Revision ID: eed16f8af036
Revises: 6121cf123e99
Create Date: 2024-07-20 08:01:36.933825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed16f8af036'
down_revision: Union[str, None] = '6121cf123e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_parent_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tasks_parent_id_fkey', 'tasks', 'tasks', ['parent_id'], ['id'])
    # ### end Alembic commands ###
